package com.webproject.bookstore.model.dal.hibrnate.entities;
// Generated Mar 22, 2019 5:44:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookOrder generated by hbm2java
 */
@Entity
@Table(name="book_order"
    ,catalog="bookstoredb"
)
public class BookOrder  implements java.io.Serializable {


     private BookOrderId id;
     private Book book;
     private UserOrder userOrder;
     private Date deliveryDate;
     private int quantity;
     private double price;

    public BookOrder() {
    }

    public BookOrder(BookOrderId id, Book book, UserOrder userOrder, Date deliveryDate, int quantity, double price) {
       this.id = id;
       this.book = book;
       this.userOrder = userOrder;
       this.deliveryDate = deliveryDate;
       this.quantity = quantity;
       this.price = price;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orderId", column=@Column(name="orderID", nullable=false) ), 
        @AttributeOverride(name="bookId", column=@Column(name="bookID", nullable=false) ) } )
    public BookOrderId getId() {
        return this.id;
    }
    
    public void setId(BookOrderId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="bookID", nullable=false, insertable=false, updatable=false)
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="orderID", nullable=false, insertable=false, updatable=false)
    public UserOrder getUserOrder() {
        return this.userOrder;
    }
    
    public void setUserOrder(UserOrder userOrder) {
        this.userOrder = userOrder;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="deliveryDate", nullable=false, length=10)
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="price", nullable=false, precision=22, scale=0)
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


