package com.webproject.bookstore.model.dal.hibrnate.entities;
// Generated Mar 22, 2019 5:44:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Offer generated by hbm2java
 */
@Entity
@Table(name="offer"
    ,catalog="bookstoredb"
)
public class Offer  implements java.io.Serializable {


     private int offerId;
     private int offerPercentage;
     private Date expireDate;
     private Set<Book> books = new HashSet<Book>(0);

    public Offer() {
    }

	
    public Offer(int offerId, int offerPercentage, Date expireDate) {
        this.offerId = offerId;
        this.offerPercentage = offerPercentage;
        this.expireDate = expireDate;
    }
    public Offer(int offerId, int offerPercentage, Date expireDate, Set<Book> books) {
       this.offerId = offerId;
       this.offerPercentage = offerPercentage;
       this.expireDate = expireDate;
       this.books = books;
    }
   
     @Id 

    
    @Column(name="offerID", unique=true, nullable=false)
    public int getOfferId() {
        return this.offerId;
    }
    
    public void setOfferId(int offerId) {
        this.offerId = offerId;
    }

    
    @Column(name="offerPercentage", nullable=false)
    public int getOfferPercentage() {
        return this.offerPercentage;
    }
    
    public void setOfferPercentage(int offerPercentage) {
        this.offerPercentage = offerPercentage;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expireDate", nullable=false, length=10)
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="offer")
    public Set<Book> getBooks() {
        return this.books;
    }
    
    public void setBooks(Set<Book> books) {
        this.books = books;
    }




}


