package com.webproject.bookstore.model.dal.hibrnate.entities;
// Generated Mar 22, 2019 5:44:23 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserCartBook generated by hbm2java
 */
@Entity
@Table(name="user_cart_book"
    ,catalog="bookstoredb"
)
public class UserCartBook {


     private UserCartBookId id;
     private Book book;
     private User user;
     private int reqQuantity;
     private int availableQuantity;

    public UserCartBook() {
    }

    public UserCartBook(UserCartBookId id, Book book, User user, int reqQuantity, int availableQuantity) {
       this.id = id;
       this.book = book;
       this.user = user;
       this.reqQuantity = reqQuantity;
       this.availableQuantity = availableQuantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="userID", nullable=false) ), 
        @AttributeOverride(name="bookId", column=@Column(name="bookID", nullable=false) ) } )
    public UserCartBookId getId() {
        return this.id;
    }
    
    public void setId(UserCartBookId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bookID", nullable=false, insertable=false, updatable=false)
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userID", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="reqQuantity", nullable=false)
    public int getReqQuantity() {
        return this.reqQuantity;
    }
    
    public void setReqQuantity(int reqQuantity) {
        this.reqQuantity = reqQuantity;
    }

    
    @Column(name="availableQuantity", nullable=false)
    public int getAvailableQuantity() {
        return this.availableQuantity;
    }
    
    public void setAvailableQuantity(int availableQuantity) {
        this.availableQuantity = availableQuantity;
    }




}


