package com.webproject.bookstore.model.dal.hibrnate.entities;
// Generated Mar 22, 2019 5:44:23 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserVisitBook generated by hbm2java
 */
@Entity
@Table(name="user_visit_book"
    ,catalog="bookstoredb"
)
public class UserVisitBook  implements java.io.Serializable {


     private UserVisitBookId id;
     private Book book;
     private User user;
     private int visitsNumber;

    public UserVisitBook() {
    }

    public UserVisitBook(UserVisitBookId id, Book book, User user, int visitsNumber) {
       this.id = id;
       this.book = book;
       this.user = user;
       this.visitsNumber = visitsNumber;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="userID", nullable=false) ), 
        @AttributeOverride(name="bookId", column=@Column(name="bookID", nullable=false) ) } )
    public UserVisitBookId getId() {
        return this.id;
    }
    
    public void setId(UserVisitBookId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bookID", nullable=false, insertable=false, updatable=false)
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userID", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="visitsNumber", nullable=false)
    public int getVisitsNumber() {
        return this.visitsNumber;
    }
    
    public void setVisitsNumber(int visitsNumber) {
        this.visitsNumber = visitsNumber;
    }




}


