package com.webproject.bookstore.model.dal.hibrnate.entities;
// Generated Mar 22, 2019 5:44:23 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserOrder generated by hbm2java
 */
@Entity
@Table(name="user_order"
    ,catalog="bookstoredb"
)
public class UserOrder  implements java.io.Serializable {


     private Integer orderId;
     private User user;
     private Set<BookOrder> bookOrders = new HashSet<BookOrder>(0);

    public UserOrder() {
    }

	
    public UserOrder(User user) {
        this.user = user;
    }
    public UserOrder(User user, Set<BookOrder> bookOrders) {
       this.user = user;
       this.bookOrders = bookOrders;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="orderID", unique=true, nullable=false)
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userID", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userOrder")
    public Set<BookOrder> getBookOrders() {
        return this.bookOrders;
    }
    
    public void setBookOrders(Set<BookOrder> bookOrders) {
        this.bookOrders = bookOrders;
    }




}


